// <auto-generated />
namespace Assignment_8.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class a8migration4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(a8migration4));
        
        string IMigrationMetadata.Id
        {
            get { return "201604081712444_a8migration4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
